language: java
services:
  - postgresql
before_script:
  - psql -c 'create user ords superuser;' -U postgres
  - psql -c 'create database ordstest owner ords;' -U postgres

after_success:
  - test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings settings.xml

env:
  global:
    - secure: "bK5SMZtIMUgzC80SJE33fvS8ILZZnGjMHqTmfAV1M9Mbxy4cYki0kLjTH/mjzk1mSsKCu9TM33hCTk3z66xUmrV4xaDdiQnZGE2x26CBr8mYDfDJ11X7xJT2aQbF2cOJaYQP2rpBlArJ821d0JiN+qYByuyflG7VIFOACegdXMgSCu3VlWzyF+LS5/bIgFtvxzy7vrSALCeeQkuIVZTf8A7xYFS5QRIDDqGsHlXLiSXd0JjEBznCO2zZpog+dy9o6ScWcTQv/YoguRR7BQnQaNqMwkKc53gis/XnaraI/X+/ToTpB3rcFiie3XC2BuO5/J/hziHD2D1xVI/SxGiuKDyGAkqfwXlq2QyNaaATmqobE5mv2f0CyL6z4ISZZc63ePDl9F/8PeTFbtvWpbO9xrGUqg+IUcVR6Gx9k3EgCUY0q9qwpnwm9ck3NvPapLSApxtC1niuR5pOwYxq8lu4PLBwf7jMfOMl1ecCLOcavZMHwSiZdq5r8C6i1u6kHO6niKr+Tuh7v78632a46Yvi2iIpyvosU8R/1kHEZ3DseUBen9i+EvwN574WJ5RJR8i/xREefUqGk+TlinrFAsASJWLBpHtAtUYHE40IT/cEPQzFordZLbgviOdSan8nDX9N3JjEP4THCLZOcEbVtgCsMRv/JNSGAHzGcau+o43C4aU="
    - secure: "WcFS8e++FJbVNQhjJmtwuQM3pTdNYEL+m/wjGMcpuESTHFrgeny4RBerdv5xJny5078A+yae85PxKv47Po07SknhvdGB+f1fFMp7x0XGye/OwvsAI665Di14GA+dDcUI2/Qy69G2itTYkzDwCz2gjMu/4zHPxZpUk7huEQNkhM7IoeJOhtlj9yP7PBebHD+N3CRQ6HfuW6vyYe1c12KNxG5rn7QwgP0+C8pEzotBUZ78dXgbAfKY7zXax/WOqWr3hKRj97w3bKGeoEd7tNA7NLqCUPsxQEZLhec16x804612g/49zr+bk4d4weeMllZkx9SDWU8wSUEER85djl0aIPxsda+K5luOPzsbTL36rzFq2zuMudIaq7BhVfi7gmPD/hxk9BBQ0onv78bOk45pGOJRUUAZJAH6OO10Ubl4k6fDDgY8L3fHTF9EufjSVJXTTCDy4FETVkHUIiTtjV4qvUK8/+3eo00pfT3niHhsGHZtENstesUPGtGifxLvMC6l5G3u34EKb0yNq50yQylVq9TStFjLFPACbWiDN1fDXyrRaOANpVLJ98MllM/Y3PIKVzMODmJF27p5Wm7hDlyzAJz2oPC18yYMhA70yu2EZoo1nCZgCm4MgR4IMAm1tby0n38bqVyMbh1ZZAkJTij4pNaUjtD3i9XpBLjYRoOu/sA="
   